"""Add audit_logs table

Revision ID: 4066e1e45ff2
Revises: aa08abe2e642
Create Date: 2025-07-15 13:38:10.013882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4066e1e45ff2'
down_revision: Union[str, Sequence[str], None] = 'aa08abe2e642'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=6),
               type_=sa.Enum('PAID', 'UNPAID', 'OVERDUE', name='invoicestatusenum'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('PAID', 'UNPAID', 'OVERDUE', name='invoicestatusenum'),
               type_=sa.VARCHAR(length=6),
               existing_nullable=False)

    # ### end Alembic commands ###
